services:
  - type: web
    name: ecovillage-builder
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true